[build]
  command = "pwd && ln -s README.md static/output.md && ls -lah /opt/build/repo"
  publish = "static"
[build.environment]
  YARN_VERSION = "1.10.1"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
