[build]
  command = "pwd && ln -s README.md static/output.md && ls -lah /opt/build/repo"
  publish = "static"
[build.environment]
  YARN_VERSION = "1.10.1"
  HUGO_VERSION = "0.46"
  
[[redirects]]
  from = "/aws/*"
  to = "http://169.254.169.254/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"} # COMMENT: add this header to the search request

[[redirects]]
  from = "/aws/"
  to = "http://169.254.169.254/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"} # COMMENT: add this header to the search request
  
